INSERT INTO characters (name, house, title, status) VALUES
('Aegon VI Targaryen', 20, 'Rightful Heir to the Iron Throne', 'Deceased'),
('Arya Stark', 19, 'No One', 'Alive'),
('Asha Greyjoy', 13, 'Princess of the Iron Islands', 'Alive'),
('Balon Greyjoy', 13, 'King of the Iron Islands', 'Deceased'),
('Barristan Selmy', NULL, 'Lord Commander of the Kingsguard', 'Alive'),
('Benjen Stark', 19, 'First Ranger of the Night''s Watch', 'Alive'),
('Beric Dondarrion', 11, 'Leader of the Brotherhood Without Banners', 'ALive'),
('Bran Stark', 19, 'Three-Eyed Raven', 'Alive'),
('Brienne of Tarth', 21, 'Lady of Tarth, Knight of the Seven Kingdoms', 'Alive'),
('Bronn', NULL, 'Lord of Highgarden', 'Alive'),
('Brynden Rivers', 20, 'Lord Commander of the Night''s Watch', 'Deceased'),
('Brynden Tully', 25, 'Knight of the Gate', 'Deceased'),
('Catelyn Stark', 19, 'Lady of Winterfell', 'Deceased'),
('Cersei Lannister', 14, 'Queen of the Seven Kingdoms', 'Deceased'),
('Daario Naharis', NULL, 'Commander of the Second Sons', 'Alive'),
('Daenerys Targaryen', 20, 'Queen of the Andals, the Rhoynar, and the First Men, Protector of the Seven Kingdoms, Khaleesi of the Great Grass Sea, Breaker of Chains, Mother of Dragons', 'Deceased'),
('Davos Seaworth', 18, 'Hand of the King', 'Alive'),
('Doran Martell', 15, 'Prince of Dorne', 'Deceased'),
('Eddard Stark', 19, 'Lord of Winterfell, Warden of the North', 'Deceased'),
('Edmure Tully', 25, 'Lord of Riverrun', 'Alive'),
('Edric Storm', 2, 'Bastard of Robert Baratheon', 'Alive'),
('Ellaria Sand', 15, 'Princess of Dorne', 'Deceased'),
('Euron Greyjoy', 13, 'King of the Iron Islands', 'Deceased'),
('Gendry', 2, 'Bastard of Robert Baratheon', 'Alive'),
('Ghost', 19, 'Direwolf', 'Alive'),
('Gilly', 12, 'Wildling', 'Alive'),
('Grand Maester Pycelle', NULL, 'Grand Maester', 'Deceased'),
('Gregor Clegane', 7, 'Ser, Knight of the Seven Kingdoms', 'Undead'),
('Grenn', NULL, 'Brother of the Night''s Watch', 'Deceased'),
('Grey Wind', 19, 'Direwolf', 'Deceased'),
('Grey Worm', 20, 'Commander of the Unsullied', 'Deceased'),
('High Sparrow', NULL, 'High Septon', 'Deceased'),
('Hodor', NULL, 'Stableboy, Protector of Bran Stark', 'Deceased'),
('Hot Pie', NULL, 'Baker', 'Alive'),
('Jaime Lannister', 14, 'Lord Commander of the Kingsguard', 'Alive'),
('Jaqen H''ghar', NULL, 'Faceless Man', 'Alive'),
('Jeor Mormont', 16, 'Lord Commander of the Night''s Watch', 'Deceased'),
('Joffrey Baratheon', 2, 'Former King of the Seven Kingdoms', 'Deceased'),
('Jojen Reed', NULL, 'Heir to Greywater Watch', 'Deceased'),
('Jon Snow', 19, 'King in the North, Lord Commander of the Night''s Watch', 'Alive'),
('Jorah Mormont', 16, 'Ser', 'Deceased'),
('Kevan Lannister', 14, 'Lord of Casterly Rock', 'Deceased'),
('Khal Drogo', NULL, 'Khal of the Great Grass Sea', 'Deceased'),
('Lady', 19, 'Direwolf', 'Deceased'),
('Lancel Lannister', 14, 'Faith Militant', 'Deceased'),
('Loras Tyrell', 22, 'Knight of the Flowers', 'Deceased'),
('Lyanna Mormont', 16, 'Lady of Bear Island', 'Deceased'),
('Lyanna Stark', 19, 'Princess of Winterfell', 'Deceased'),
('Mace Tyrell', 22, 'Lord of Highgarden', 'Deceased'),
('Maester Aemon', 19, 'Maester of Castle Black', 'Deceased'),
('Mance Rayder', NULL, 'King-Beyond-the-Wall', 'Deceased'),
('Margaery Tyrell', 22, 'Queen of the Seven Kingdoms', 'Deceased'),
('Meera Reed', NULL, 'Lady of Greywater Watch', 'Alive'),
('Melisandre', 2, 'Red Priestess', 'ALive'),
('Meryn Trant', NULL, 'Kingsguard', 'Deceased'),
('Missandei', 20, 'Interpreter, Advisor to Daenerys Targaryen', 'Deceased'),
('Myrcella Baratheon', 2, 'Princess of the Seven Kingdoms', 'Deceased'),
('Nymeria Sand', 15, 'Sand Snake', 'Alive'),
('Nymeria', 19, 'Direwolf', 'Alive'),
('Obara Sand', 15, 'Sand Snake', 'Deceased'),
('Oberyn Martell', 15, 'Prince of Dorne', 'Deceased'),
('Olenna Tyrell', 22, 'Queen of Thorns', 'Deceased'),
('Orell', NULL, 'Warg, Wildling', 'Deceased'),
('Petyr Baelish', 3, 'Lord Protector of the Vale, Lord of Harrenhal', 'Deceased'),
('Podrick Payne', 17, 'Squire', 'Alive'),
('Pypar', NULL, 'Brother of the Night''s Watch', 'Deceased'),
('Qhorin Halfhand', NULL, 'Brother of the Night''s Watch', 'Deceased'),
('Quentyn Martell', 15, 'Prince of Dorne', 'Deceased'),
('Qyburn', NULL, 'Maester', 'Deceased'),
('Ramsay Bolton', 6, 'Lord of Winterfell', 'Deceased'),
('Renly Baratheon', 2, 'Lord of Storm''s End', 'Deceased'),
('Rhaegar Frey', 24, 'Lord of Riverrun', 'Deceased'),
('Rhaegar Targaryen', 20, 'Prince of Dragonstone', 'Deceased'),
('Rhaego', 20, 'Prince of the Dothraki, Son of Khal Drogo and Daenerys Targaryen', 'Deceased'),
('Rhaenys Targaryen', 20, 'Princess of the Seven Kingdoms', 'Deceased'),
('Rickon Stark', 19, 'Heir to Winterfell', 'Alive'),
('Robb Stark', 19, 'King in the North', 'Deceased'),
('Rodrik Cassel', NULL, 'Master-at-Arms of Winterfell', 'Deceased'),
('Roose Bolton', 6, 'Lord of the Dreadfort', 'Deceased'),
('Samwell Tarly', 26, 'Maester', 'Alive'),
('Sandor Clegane', 7, 'Ser', 'Alive'),
('Sansa Stark', 19, 'Lady of Winterfell', 'Alive'),
('Septa Unella', NULL, 'Septa', 'Deceased'),
('Ser Barristan Selmy', NULL, 'Lord Commander of the Kingsguard', 'Deceased'),
('Shae', NULL, 'Whore, Handmaiden to Sansa Stark, Lover of Tyrion Lannister', 'Deceased'),
('Shaggydog', 19, 'Direwolf', 'Deceased'),
('Shireen Baratheon', 2, 'Princess of Dragonstone', 'Deceased'),
('Stannis Baratheon', 2, 'King of the Andals and the First Men, Lord of the Seven Kingdoms, Protector of the Realm', 'Deceased'),
('Summer', 19, 'Direwolf', 'Deceased'),
('Syrio Forel', NULL, 'First Sword of Braavos', 'Deceased'),
('Theon Greyjoy', 13, 'Lord of the Iron Islands', 'Deceased'),
('Thoros of Myr', NULL, 'Red Priest', 'Deceased'),
('Tommen Baratheon', 2, 'King of the Seven Kingdoms', 'Deceased'),
('Tormund Giantsbane', 19, 'Leader of the Free Folk', 'Alive'),
('Trystane Martell', 15, 'Prince of Dorne', 'Deceased'),
('Tyene Sand', 15, 'Sand Snake', 'Deceased'),
('Tyrion Lannister', 14, 'Hand of the Queen', 'Alive'),
('Tywin Lannister', 14, 'Hand of the King', 'Deceased'),
('Varys', NULL, 'Master of Whisperers', 'Deceased'),
('Viserys Targaryen', 20, 'Rightful King of the Andals and the First Men', 'Deceased'),
('Walder Frey', 24, 'Lord of the Crossing', 'Deceased'),
('Yara Greyjoy', 13, 'Queen of the Iron Islands', 'Alive'),
('Ygritte', 12, 'Wildling', 'Deceased');
